dist: bionic
language: php

services: 
  - docker

branches:
  only:
  - master
  - /pr\//
  - add-apache-php

  script:
    - set -e
    - echo $DOCKERHUB_PASSWORD | docker login -u="$DOCKERHUB_USERNAME" --password-stdin
    - docker-compose build
    - docker push mheiniger/palaceserver:latest-web
    - docker push mheiniger/palaceserver:latest-palace