version: "3.9"

services:
  palace:
    image: mheiniger/palaceserver:latest-palace
    ports:
      - "9998:9998"
    volumes:
      # user manageable content
      - $PWD/run/media:/app/run/media
      - $PWD/run/avatars:/app/run/avatars
      - $PWD/run/psdata:/app/run/psdata
      - $PWD/run/webservice:/app/run/webservice
      - $PWD/run/logs:/app/run/logs
    depends_on:
      - web
  web:
    image:  mheiniger/palaceserver:latest-web
    volumes:
      # user manageable content
      - $PWD/run/media:/app/run/media
      - $PWD/run/avatars:/app/run/avatars
      - $PWD/run/webservice:/app/run/webservice
      # runtime storage
      - propStorage:/app/run/webservice/propStorage
    ports:
      - "9990:9990"

volumes:
  propStorage:
